### ISSUE TITLE
Todo.

### ISSUE THREAD

**Issue by JonasMoss** [JonasMoss/semTests#1]
## Commentz
* Scaled f, scaled and shifted, og mean-variance adjusted finnes ikke for to modeller.
* Er `unname(lavaan::fitmeasures(m, fit.measures = "pvalue.scaled"))` riktig?

## p-verdiproblemer
- [x] scaled_f
- [x] scaled_and_shifted / mean_var_adjusted.
- [x] scaled_and_shifted for two models (`lavaTestLRT`).

## Første prioritet.
- [x] Fikse flergruppe bootstrapping.
- [x] Use `ugamma_non_nested` for one model.
- [x] `tml`: Difference of uncorrected `chisq`.
- [x] `pml`: Does this assume the model is fitted with ml?
- [x] Legge til bollenstine.
- [x] Paralell boostraper.
- [x] Fiks readme'n; den knittes ikke akkurat nå. (Også for å vise hvordan parallelismen funker i readmeen.)
- [x] Sjekk https://github.com/yrosseel/lavaan/blob/70200542d9947c3481743308382053f0e5d84b28/R/lav_test_satorra_bentler.R for å se om det er mer presis ugamma kode. **Dropper denne.**

## Andre prioritet.
- [x] Fikse flere modeller: bootstrap lrt.
- [x] Flere flere modeller: pvalues.
- [x] Fikse flere modeller: semselector.
- [x] Paralell boostraper.
- [x] Husk "riktig rekkefølge". `m0` er restructed-
